import { MigrationInterface, QueryRunner } from 'typeorm'

export class AppCsvRuns1744553414309 implements MigrationInterface {
    name = 'AppCsvRuns1744553414309'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."IDX_f56c36fe42894d57e5c664d229"`)
        await queryRunner.query(`DROP INDEX "public"."IDX_e76bae1780b77e56aab1h2asd4"`)
        await queryRunner.query(`DROP INDEX "public"."IDX_e213b811b01405a42309a6a410"`)
        await queryRunner.query(`DROP INDEX "public"."IDX_f56c36fe42894d57e5c664d230"`)
        await queryRunner.query(`DROP INDEX "public"."IDX_paid_plan_organizationId"`)
        await queryRunner.query(`DROP INDEX "public"."IDX_trial_plan_userId"`)
        await queryRunner.query(`DROP INDEX "public"."IDX_e6e53a2b10cf93937cb25dd6b0"`)
        await queryRunner.query(`DROP INDEX "public"."IDX_2de04cc3a17b7cbff2489bcf17"`)
        await queryRunner.query(`DROP INDEX "public"."IDX_trace_id_lookup"`)
        await queryRunner.query(
            `CREATE TABLE "app_csv_parse_runs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "organizationId" uuid NOT NULL, "startedAt" TIMESTAMP NOT NULL, "completedAt" TIMESTAMP, "rowsRequested" integer NOT NULL, "rowsProcessed" integer, "name" text NOT NULL, "configuration" json NOT NULL, "originalCsvUrl" text NOT NULL, "processedCsvUrl" text, "chatflowChatId" text NOT NULL, "includeOriginalColumns" boolean NOT NULL DEFAULT false, "status" text NOT NULL, "errorMessages" json NOT NULL, "createdDate" TIMESTAMP NOT NULL DEFAULT now(), "updatedDate" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_21b59834715d12d9455b63a496d" PRIMARY KEY ("id"))`
        )
        await queryRunner.query(`CREATE INDEX "IDX_326a632876d0cff0b71d6a57f1" ON "app_csv_parse_runs" ("userId") `)
        await queryRunner.query(`CREATE INDEX "IDX_8e72c75e3e7b5cc751fa6429fb" ON "app_csv_parse_runs" ("organizationId") `)
        await queryRunner.query(
            `CREATE TABLE "app_csv_parse_rows" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "csvParseRunId" uuid NOT NULL, "rowNumber" integer NOT NULL, "rowData" json NOT NULL, "generatedData" json, "status" text NOT NULL, "errorMessage" text, "createdAt" TIMESTAMP NOT NULL, "updatedAt" TIMESTAMP NOT NULL, CONSTRAINT "PK_9d839afdaafe641a70bd747944d" PRIMARY KEY ("id"))`
        )
        await queryRunner.query(`CREATE INDEX "IDX_fd8dacb78914b50e53dba611ee" ON "app_csv_parse_rows" ("csvParseRunId") `)
        await queryRunner.query(`DROP INDEX "public"."IDX_442b9a2cff872736117c8742b1"`)
        await queryRunner.query(`ALTER TABLE "chat_flow" DROP COLUMN "parentChatflowId"`)
        await queryRunner.query(`ALTER TABLE "chat_flow" ADD "parentChatflowId" text`)
        await queryRunner.query(`ALTER TABLE "chat_message" ALTER COLUMN "chatType" DROP DEFAULT`)
        await queryRunner.query(`ALTER TABLE "lead" DROP COLUMN "name"`)
        await queryRunner.query(`ALTER TABLE "lead" ADD "name" character varying NOT NULL`)
        await queryRunner.query(`ALTER TABLE "lead" DROP COLUMN "email"`)
        await queryRunner.query(`ALTER TABLE "lead" ADD "email" character varying NOT NULL`)
        await queryRunner.query(`ALTER TABLE "lead" DROP COLUMN "phone"`)
        await queryRunner.query(`ALTER TABLE "lead" ADD "phone" character varying NOT NULL`)
        await queryRunner.query(`ALTER TABLE "document_store" DROP COLUMN "name"`)
        await queryRunner.query(`ALTER TABLE "document_store" ADD "name" text NOT NULL`)
        await queryRunner.query(`ALTER TABLE "document_store" DROP COLUMN "description"`)
        await queryRunner.query(`ALTER TABLE "document_store" ADD "description" text`)
        await queryRunner.query(`ALTER TABLE "document_store" DROP COLUMN "status"`)
        await queryRunner.query(`ALTER TABLE "document_store" ADD "status" text NOT NULL`)
        await queryRunner.query(`ALTER TABLE "document_store_file_chunk" ALTER COLUMN "pageContent" SET NOT NULL`)
        await queryRunner.query(`ALTER TABLE "chat_message_feedback" ALTER COLUMN "rating" DROP NOT NULL`)
        await queryRunner.query(`ALTER TABLE "upsert_history" DROP COLUMN "result"`)
        await queryRunner.query(`ALTER TABLE "upsert_history" ADD "result" character varying NOT NULL`)
        await queryRunner.query(`ALTER TABLE "upsert_history" DROP COLUMN "flowData"`)
        await queryRunner.query(`ALTER TABLE "upsert_history" ADD "flowData" character varying NOT NULL`)
        await queryRunner.query(`ALTER TABLE "apikey" DROP CONSTRAINT "PK_96109043dd704f53-9830ab78f0"`)
        await queryRunner.query(`ALTER TABLE "apikey" DROP COLUMN "id"`)
        await queryRunner.query(`ALTER TABLE "apikey" ADD "id" character varying(20) NOT NULL`)
        await queryRunner.query(`ALTER TABLE "apikey" ADD CONSTRAINT "PK_0a1358bea3e5a3ba047b6e4959c" PRIMARY KEY ("id")`)
        await queryRunner.query(`ALTER TABLE "apikey" DROP COLUMN "apiKey"`)
        await queryRunner.query(`ALTER TABLE "apikey" ADD "apiKey" text NOT NULL`)
        await queryRunner.query(`ALTER TABLE "apikey" DROP COLUMN "apiSecret"`)
        await queryRunner.query(`ALTER TABLE "apikey" ADD "apiSecret" text NOT NULL`)
        await queryRunner.query(`ALTER TABLE "apikey" DROP COLUMN "keyName"`)
        await queryRunner.query(`ALTER TABLE "apikey" ADD "keyName" text NOT NULL`)
        await queryRunner.query(`ALTER TABLE "apikey" DROP COLUMN "metadata"`)
        await queryRunner.query(`ALTER TABLE "apikey" ADD "metadata" text`)
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "organizationId" SET NOT NULL`)
        await queryRunner.query(`ALTER TABLE "paid_plan" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`)
        await queryRunner.query(`ALTER TABLE "trial_plan" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`)
        await queryRunner.query(`ALTER TABLE "usage_event" DROP COLUMN "stripeCustomerId"`)
        await queryRunner.query(`ALTER TABLE "usage_event" ADD "stripeCustomerId" character varying NOT NULL`)
        await queryRunner.query(`DROP INDEX "public"."IDX_f55608e2ecbb73851d47bdca71"`)
        await queryRunner.query(`ALTER TABLE "usage_event" DROP COLUMN "organizationId"`)
        await queryRunner.query(`ALTER TABLE "usage_event" ADD "organizationId" uuid`)
        await queryRunner.query(`ALTER TABLE "custom_template" DROP COLUMN "description"`)
        await queryRunner.query(`ALTER TABLE "custom_template" ADD "description" text`)
        await queryRunner.query(`ALTER TABLE "custom_template" DROP COLUMN "badge"`)
        await queryRunner.query(`ALTER TABLE "custom_template" ADD "badge" text`)
        await queryRunner.query(`ALTER TABLE "custom_template" DROP COLUMN "framework"`)
        await queryRunner.query(`ALTER TABLE "custom_template" ADD "framework" text`)
        await queryRunner.query(`ALTER TABLE "custom_template" DROP COLUMN "usecases"`)
        await queryRunner.query(`ALTER TABLE "custom_template" ADD "usecases" text`)
        await queryRunner.query(`ALTER TABLE "custom_template" DROP COLUMN "type"`)
        await queryRunner.query(`ALTER TABLE "custom_template" ADD "type" text`)
        await queryRunner.query(`CREATE INDEX "IDX_442b9a2cff872736117c8742b1" ON "chat_flow" ("parentChatflowId") `)
        await queryRunner.query(`CREATE INDEX "IDX_f56c36fe42894d57e5c664d229" ON "chat_message_feedback" ("chatflowid") `)
        await queryRunner.query(`CREATE INDEX "IDX_4572bbe0437c04b9842d802a0c" ON "upsert_history" ("chatflowid") `)
        await queryRunner.query(`CREATE INDEX "IDX_7bf44502ed80d501adc5086b50" ON "paid_plan" ("organizationId") `)
        await queryRunner.query(`CREATE INDEX "IDX_a2200e5d14c95730c1cfb3f9d2" ON "trial_plan" ("userId") `)
        await queryRunner.query(`CREATE INDEX "IDX_f17d482977e6a0a1eb2f64dc2a" ON "usage_event" ("stripeCustomerId") `)
        await queryRunner.query(`CREATE INDEX "IDX_be802331bd54f3348cbbe100c8" ON "usage_event" ("userId") `)
        await queryRunner.query(`CREATE INDEX "IDX_f55608e2ecbb73851d47bdca71" ON "usage_event" ("organizationId") `)
        await queryRunner.query(`CREATE INDEX "IDX_5755b028376acc57654b830cb2" ON "usage_event" ("traceId") `)
        await queryRunner.query(
            `ALTER TABLE "chat" ADD CONSTRAINT "FK_64635a7018308a5399c37eb1932" FOREIGN KEY ("chatflowId") REFERENCES "chat_flow"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`
        )
        await queryRunner.query(
            `ALTER TABLE "chat" ADD CONSTRAINT "FK_ae88d8de23e69a0d57105a5bce5" FOREIGN KEY ("ownerId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`
        )
        await queryRunner.query(
            `ALTER TABLE "chat" ADD CONSTRAINT "FK_2630d5ea3b9b8a5457ce97abb14" FOREIGN KEY ("organizationId") REFERENCES "organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`
        )
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "chat" DROP CONSTRAINT "FK_2630d5ea3b9b8a5457ce97abb14"`)
        await queryRunner.query(`ALTER TABLE "chat" DROP CONSTRAINT "FK_ae88d8de23e69a0d57105a5bce5"`)
        await queryRunner.query(`ALTER TABLE "chat" DROP CONSTRAINT "FK_64635a7018308a5399c37eb1932"`)
        await queryRunner.query(`DROP INDEX "public"."IDX_5755b028376acc57654b830cb2"`)
        await queryRunner.query(`DROP INDEX "public"."IDX_f55608e2ecbb73851d47bdca71"`)
        await queryRunner.query(`DROP INDEX "public"."IDX_be802331bd54f3348cbbe100c8"`)
        await queryRunner.query(`DROP INDEX "public"."IDX_f17d482977e6a0a1eb2f64dc2a"`)
        await queryRunner.query(`DROP INDEX "public"."IDX_a2200e5d14c95730c1cfb3f9d2"`)
        await queryRunner.query(`DROP INDEX "public"."IDX_7bf44502ed80d501adc5086b50"`)
        await queryRunner.query(`DROP INDEX "public"."IDX_4572bbe0437c04b9842d802a0c"`)
        await queryRunner.query(`DROP INDEX "public"."IDX_f56c36fe42894d57e5c664d229"`)
        await queryRunner.query(`DROP INDEX "public"."IDX_442b9a2cff872736117c8742b1"`)
        await queryRunner.query(`ALTER TABLE "custom_template" DROP COLUMN "type"`)
        await queryRunner.query(`ALTER TABLE "custom_template" ADD "type" character varying`)
        await queryRunner.query(`ALTER TABLE "custom_template" DROP COLUMN "usecases"`)
        await queryRunner.query(`ALTER TABLE "custom_template" ADD "usecases" character varying`)
        await queryRunner.query(`ALTER TABLE "custom_template" DROP COLUMN "framework"`)
        await queryRunner.query(`ALTER TABLE "custom_template" ADD "framework" character varying`)
        await queryRunner.query(`ALTER TABLE "custom_template" DROP COLUMN "badge"`)
        await queryRunner.query(`ALTER TABLE "custom_template" ADD "badge" character varying`)
        await queryRunner.query(`ALTER TABLE "custom_template" DROP COLUMN "description"`)
        await queryRunner.query(`ALTER TABLE "custom_template" ADD "description" character varying`)
        await queryRunner.query(`ALTER TABLE "usage_event" DROP COLUMN "organizationId"`)
        await queryRunner.query(`ALTER TABLE "usage_event" ADD "organizationId" character varying(50)`)
        await queryRunner.query(`CREATE INDEX "IDX_f55608e2ecbb73851d47bdca71" ON "usage_event" ("organizationId") `)
        await queryRunner.query(`ALTER TABLE "usage_event" DROP COLUMN "stripeCustomerId"`)
        await queryRunner.query(`ALTER TABLE "usage_event" ADD "stripeCustomerId" character varying(50) NOT NULL`)
        await queryRunner.query(`ALTER TABLE "trial_plan" ALTER COLUMN "id" DROP DEFAULT`)
        await queryRunner.query(`ALTER TABLE "paid_plan" ALTER COLUMN "id" DROP DEFAULT`)
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "organizationId" DROP NOT NULL`)
        await queryRunner.query(`ALTER TABLE "apikey" DROP COLUMN "metadata"`)
        await queryRunner.query(`ALTER TABLE "apikey" ADD "metadata" jsonb`)
        await queryRunner.query(`ALTER TABLE "apikey" DROP COLUMN "keyName"`)
        await queryRunner.query(`ALTER TABLE "apikey" ADD "keyName" character varying NOT NULL`)
        await queryRunner.query(`ALTER TABLE "apikey" DROP COLUMN "apiSecret"`)
        await queryRunner.query(`ALTER TABLE "apikey" ADD "apiSecret" character varying NOT NULL`)
        await queryRunner.query(`ALTER TABLE "apikey" DROP COLUMN "apiKey"`)
        await queryRunner.query(`ALTER TABLE "apikey" ADD "apiKey" character varying NOT NULL`)
        await queryRunner.query(`ALTER TABLE "apikey" DROP CONSTRAINT "PK_0a1358bea3e5a3ba047b6e4959c"`)
        await queryRunner.query(`ALTER TABLE "apikey" DROP COLUMN "id"`)
        await queryRunner.query(`ALTER TABLE "apikey" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`)
        await queryRunner.query(`ALTER TABLE "apikey" ADD CONSTRAINT "PK_96109043dd704f53-9830ab78f0" PRIMARY KEY ("id")`)
        await queryRunner.query(`ALTER TABLE "upsert_history" DROP COLUMN "flowData"`)
        await queryRunner.query(`ALTER TABLE "upsert_history" ADD "flowData" text NOT NULL`)
        await queryRunner.query(`ALTER TABLE "upsert_history" DROP COLUMN "result"`)
        await queryRunner.query(`ALTER TABLE "upsert_history" ADD "result" text NOT NULL`)
        await queryRunner.query(`ALTER TABLE "chat_message_feedback" ALTER COLUMN "rating" SET NOT NULL`)
        await queryRunner.query(`ALTER TABLE "document_store_file_chunk" ALTER COLUMN "pageContent" DROP NOT NULL`)
        await queryRunner.query(`ALTER TABLE "document_store" DROP COLUMN "status"`)
        await queryRunner.query(`ALTER TABLE "document_store" ADD "status" character varying NOT NULL`)
        await queryRunner.query(`ALTER TABLE "document_store" DROP COLUMN "description"`)
        await queryRunner.query(`ALTER TABLE "document_store" ADD "description" character varying`)
        await queryRunner.query(`ALTER TABLE "document_store" DROP COLUMN "name"`)
        await queryRunner.query(`ALTER TABLE "document_store" ADD "name" character varying NOT NULL`)
        await queryRunner.query(`ALTER TABLE "lead" DROP COLUMN "phone"`)
        await queryRunner.query(`ALTER TABLE "lead" ADD "phone" text`)
        await queryRunner.query(`ALTER TABLE "lead" DROP COLUMN "email"`)
        await queryRunner.query(`ALTER TABLE "lead" ADD "email" text`)
        await queryRunner.query(`ALTER TABLE "lead" DROP COLUMN "name"`)
        await queryRunner.query(`ALTER TABLE "lead" ADD "name" text`)
        await queryRunner.query(`ALTER TABLE "chat_message" ALTER COLUMN "chatType" SET DEFAULT 'INTERNAL'`)
        await queryRunner.query(`ALTER TABLE "chat_flow" DROP COLUMN "parentChatflowId"`)
        await queryRunner.query(`ALTER TABLE "chat_flow" ADD "parentChatflowId" uuid`)
        await queryRunner.query(`CREATE INDEX "IDX_442b9a2cff872736117c8742b1" ON "chat_flow" ("parentChatflowId") `)
        await queryRunner.query(`DROP INDEX "public"."IDX_fd8dacb78914b50e53dba611ee"`)
        await queryRunner.query(`DROP TABLE "app_csv_parse_rows"`)
        await queryRunner.query(`DROP INDEX "public"."IDX_8e72c75e3e7b5cc751fa6429fb"`)
        await queryRunner.query(`DROP INDEX "public"."IDX_326a632876d0cff0b71d6a57f1"`)
        await queryRunner.query(`DROP TABLE "app_csv_parse_runs"`)
        await queryRunner.query(`CREATE INDEX "IDX_trace_id_lookup" ON "usage_event" ("traceId") `)
        await queryRunner.query(`CREATE INDEX "IDX_2de04cc3a17b7cbff2489bcf17" ON "usage_event" ("userId") `)
        await queryRunner.query(`CREATE INDEX "IDX_e6e53a2b10cf93937cb25dd6b0" ON "usage_event" ("stripeCustomerId") `)
        await queryRunner.query(`CREATE INDEX "IDX_trial_plan_userId" ON "trial_plan" ("userId") `)
        await queryRunner.query(`CREATE INDEX "IDX_paid_plan_organizationId" ON "paid_plan" ("organizationId") `)
        await queryRunner.query(`CREATE INDEX "IDX_f56c36fe42894d57e5c664d230" ON "chat_message_feedback" ("chatflowid") `)
        await queryRunner.query(`CREATE INDEX "IDX_e213b811b01405a42309a6a410" ON "document_store_file_chunk" ("storeId") `)
        await queryRunner.query(`CREATE INDEX "IDX_e76bae1780b77e56aab1h2asd4" ON "document_store_file_chunk" ("docId") `)
        await queryRunner.query(`CREATE INDEX "IDX_f56c36fe42894d57e5c664d229" ON "chat_message" ("chatflowid") `)
    }
}
