version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'daily'
      target-branch: 'staging'
      open-pull-requests-limit: 10
    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'daily'
      target-branch: 'staging'
      open-pull-requests-limit: 10
