packages:
    - 'apps/web'
    - 'apps/desktop'
    - 'packages-answers/*'
    - 'packages/components'
    - 'packages/server'
    - 'packages/ui'
    - 'packages/embed'
    - 'packages/embed-react'
    - 'packages/docs'
    - 'packages/api-documentation'
