[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "pnpm start"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
FLOWISE_USERNAME = "${FLOWISE_USERNAME}"
FLOWISE_PASSWORD = "${FLOWISE_PASSWORD}"
PORT = "3000"
DATABASE_PATH = "/usr/src/packages/server/.flowise"
APIKEY_PATH = "/usr/src/packages/server/.flowise"
SECRETKEY_PATH = "/usr/src/packages/server/.flowise"
LOG_PATH = "/usr/src/packages/server/logs"
EXECUTION_PATH = "/usr/src/packages/server/dist"