[build]
builder = "DOCKERFILE"
dockerfilePath = "docker/Dockerfile.railway"

[deploy]
startCommand = "node packages/server/dist/index.js"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
FLOWISE_USERNAME = "${FLOWISE_USERNAME}"
FLOWISE_PASSWORD = "${FLOWISE_PASSWORD}"
PORT = "3000"
DATABASE_PATH = "/data/.flowise"
APIKEY_PATH = "/data/.flowise"
SECRETKEY_PATH = "/data/.flowise"
LOG_PATH = "/data/logs"
EXECUTION_PATH = "/app/packages/server/dist"