AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for Flowise Application Load Balancer'

Parameters:
  Stage:
    Description: Prefix of resource names
    Type: String
    Default: sumo-flowise

  Environment:
    Description: "Deployment environment (e.g., dev, prod)"
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

  SumoFlowiseCertificateArn:
    Description: Certificate ARN
    Type: String

Resources:
  # Security Group for ALB
  SumoFlowiseLoadBalancerSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !ImportValue 
        Fn::Join: ["-", [!Ref Stage, "VPCId", !Ref Environment]]
      GroupDescription: Security group for Flowise ALB
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Join ["-", [!Ref Stage, "loadbalancer-sg", !Ref Environment]]
        - Key: Environment
          Value: !Ref Environment

  # Application Load Balancer
  SumoFlowiseLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Join ["-", [!Ref Stage, "loadbalancer", !Ref Environment]]
      Scheme: internet-facing
      Subnets:
        - !ImportValue 
          Fn::Join: ["-", [!Ref Stage, "Public1Id", !Ref Environment]]
        - !ImportValue 
          Fn::Join: ["-", [!Ref Stage, "Public2Id", !Ref Environment]]
      SecurityGroups:
        - !Ref SumoFlowiseLoadBalancerSG
      IpAddressType: ipv4
      Tags:
        - Key: Name
          Value: !Join ["-", [!Ref Stage, "loadbalancer", !Ref Environment]]
        - Key: Environment
          Value: !Ref Environment

  # Target Group for Flowise Instances
  SumoFlowiseTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Join ["-", [!Ref Stage, "tg", !Ref Environment]]
      VpcId: !ImportValue 
        Fn::Join: ["-", [!Ref Stage, "VPCId", !Ref Environment]]
      Protocol: HTTP
      Port: 3000
      TargetType: instance
      HealthCheckProtocol: HTTP
      HealthCheckPort: 3000
      HealthCheckPath: /api
      Matcher:
        HttpCode: 200

  # Listener for HTTP
  SumoFlowiseHTTPListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref SumoFlowiseLoadBalancer
      Protocol: HTTP
      Port: 80
      DefaultActions:
        - Type: redirect
          RedirectConfig:
            Protocol: HTTPS
            Port: "443"
            StatusCode: HTTP_301

  # Listener for HTTPS
  SumoFlowiseHTTPSListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref SumoFlowiseLoadBalancer
      Protocol: HTTPS
      Port: 443
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref SumoFlowiseTargetGroup
      Certificates:
        - CertificateArn: !Ref SumoFlowiseCertificateArn

Outputs:
  SumoFlowiseLoadBalancerSGId:
    Description: 'The ID of the load balancer'
    Value: !Ref SumoFlowiseLoadBalancerSG
    Export:
      Name: !Join ["-", [!Ref Stage, "LoadbalancerSGId", !Ref Environment]]

  SumoFlowiseLoadBalancerDNSName:
    Description: 'DNS name of the load balancer'
    Value: !GetAtt SumoFlowiseLoadBalancer.DNSName
    Export:
      Name: !Join ["-", [!Ref Stage, "LoadbalancerDNSName", !Ref Environment]]

  SumoFlowiseLoadBalancerCanonicalHostedZoneId:
    Description: 'CanonicalHostedZoneId of the load balancer'
    Value: !GetAtt SumoFlowiseLoadBalancer.CanonicalHostedZoneID
    Export:
      Name: !Join ["-", [!Ref Stage, "LoadbalancerCanonicalHostedZoneId", !Ref Environment]]

  SumoFlowiseTargetGroupArn:
    Description: 'The Arn of the TargetGroup'
    Value: !GetAtt  SumoFlowiseTargetGroup.TargetGroupArn
    Export:
      Name: !Join ["-", [!Ref Stage, "TargetGroupArn", !Ref Environment]]
