AWSTemplateFormatVersion: "2010-09-09"

Description: This template creates resources for Flowise application

Parameters:
  Stage:
    Description: Prefix of resource names
    Type: String
    Default: sumo-flowise

  CurrentEnv:
    Description: "Deployment environment (e.g., dev, prod)"
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

Resources:
  SumoFlowiseECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Join ["-", [!Ref Stage, app, !Ref CurrentEnv]]
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                  "rulePriority": 1,
                  "description": "Rule 1",
                  "selection": {
                      "tagStatus": "any",
                      "countType": "imageCountMoreThan",
                      "countNumber": 5
                  },
                  "action": {
                      "type": "expire"
                  }
              }
            ]
          }
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          - Sid: CodeBuildAccess
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action:
              - ecr:BatchCheckLayerAvailability
              - ecr:BatchGetImage
              - ecr:CompleteLayerUpload
              - ecr:DescribeImages
              - ecr:GetDownloadUrlForLayer
              - ecr:InitiateLayerUpload
              - ecr:PutImage
              - ecr:UploadLayerPart

Outputs:
  SumoFlowiseECRRepositoryUri:
    Description: 'The Repository Uri of the ECR::Repository'
    Value: !GetAtt SumoFlowiseECRRepository.RepositoryUri
    Export:
      Name: !Join ["-", [!Ref Stage, ECRRepositoryUri, !Ref CurrentEnv]]
