AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for Redis ElastiCache setup for Flowise'

Parameters:
  Stage:
    Description: Prefix of resource names
    Type: String
    Default: sumo-flowise

  Environment:
    Description: "Deployment environment (e.g., dev, prod)"
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    
Resources:
  # Security Group for Redis
  SumoFlowiseRedisSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !ImportValue 
        Fn::Join: ["-", [!Ref Stage, "VPCId", !Ref Environment]]
      GroupDescription: Security group for Flowise Redis
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
          SourceSecurityGroupId: !ImportValue 
            Fn::Join: ["-", [!Ref Stage, "LoadbalancerSGId", !Ref Environment]]
      Tags:
        - Key: Name
          Value: !Join ["-", [!Ref Stage, "redis-sg", !Ref Environment]]
        - Key: Environment
          Value: !Ref Environment

  # ElastiCache Subnet Group
  SumoFlowiseRedisSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: Subnet group for Flowise Redis
      SubnetIds:
        - !ImportValue
          Fn::Join: ["-", [!Ref Stage, "Private1Id", !Ref Environment]]
        - !ImportValue
          Fn::Join: ["-", [!Ref Stage, "Private2Id", !Ref Environment]]
      Tags:
        - Key: Name
          Value: !Join ["-", [!Ref Stage, "redis-group", !Ref Environment]]
        - Key: Environment
          Value: !Ref Environment

  # Redis Cluster
  SumoFlowiseRedisCluster:
    Type: AWS::ElastiCache::ReplicationGroup
    Properties:
      ReplicationGroupDescription: Flowise Redis cluster
      ReplicationGroupId: !Join ["-", [!Ref Stage, "redis", !Ref Environment]]
      Engine: redis
      CacheNodeType: cache.t3.micro
      NumCacheClusters: 2
      AutomaticFailoverEnabled: true
      SecurityGroupIds:
        - !Ref SumoFlowiseRedisSecurityGroup
      CacheSubnetGroupName: !Ref SumoFlowiseRedisSubnetGroup
      Tags:
        - Key: Name
          Value: !Join ["-", [!Ref Stage, "redis", !Ref Environment]]
        - Key: Environment
          Value: !Ref Environment

Outputs:
  SumoFlowiseRedisEndpointAddress:
    Description: 'Primary endpoint address for the Redis cluster'
    Value: !GetAtt SumoFlowiseRedisCluster.PrimaryEndPoint.Address
    Export:
      Name: !Join ["-", [!Ref Stage, "RedisEndpointAddress", !Ref Environment]]

  SumoFlowiseRedisEndpointPort:
    Description: 'Primary endpoint port for the Redis cluster'
    Value: !GetAtt SumoFlowiseRedisCluster.PrimaryEndPoint.Port
    Export:
      Name: !Join ["-", [!Ref Stage, "RedisEndpointPort", !Ref Environment]]
