AWSTemplateFormatVersion: "2010-09-09"

Description: This template creates resources for Flowise application

Parameters:
  Stage:
    Description: Prefix of resource names
    Type: String
    Default: sumo-flowise

  CurrentEnv:
    Description: "Deployment environment (e.g., dev, prod)"
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

Resources:
  # Create a Secret in AWS Secrets Manager
  SumoFlowiseSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Join ["-", [!Ref Stage, secret, !Ref CurrentEnv]]
      Description: "Database credentials for Flowise application"
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: "password"
        PasswordLength: 30
        ExcludeCharacters: '"@/\'
      Tags:
        - Key: Name
          Value: !Join ["-", [!Ref Stage, secret, !Ref CurrentEnv]]
        - Key: CurrentEnv
          Value: !Ref CurrentEnv

  # SumoFlowiseSecretRotation:
  #   Type: AWS::SecretsManager::RotationSchedule
  #   Properties: 
  #     SecretId: !Ref SumoFlowiseSecret
  #     RotationLambdaARN: !ImportValue PostgreSQLRotationLambdaArn
  #     RotationRules: 
  #       AutomaticallyAfterDays: 1 # Rotate every day

Outputs:
  SumoFlowiseSecretId:
    Description: 'The ID of the secret'
    Value: !Ref SumoFlowiseSecret
    Export:
      Name: !Join ["-", [!Ref Stage, SecretId, !Ref CurrentEnv]]

  SumoFlowiseSecretUsername:
    Description: 'The ID of the secret'
    Value: !Sub "${SumoFlowiseSecret}:username"
    Export:
      Name: !Join ["-", [!Ref Stage, SecretUsername, !Ref CurrentEnv]]

  SumoFlowiseSecretPassword:
    Description: 'The ID of the secret'
    Value: !Sub "${SumoFlowiseSecret}:password"
    Export:
      Name: !Join ["-", [!Ref Stage, SecretPassword, !Ref CurrentEnv]]
