AWSTemplateFormatVersion: "2010-09-09"

Description: This template creates resources for Flowise application

Parameters:
  Stage:
    Description: Prefix of resource names
    Type: String
    Default: sumo-flowise

  CurrentEnv:
    Description: "Deployment environment (e.g., dev, prod)"
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

  Username:
    Description: 'The database admin account username'
    NoEcho: true
    Type: 'String'
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: 'must begin with a letter and contain only alphanumeric characters.'

  Password:
    Description: 'The database admin account password'
    NoEcho: true
    Type: 'String'
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9@]*'
    ConstraintDescription: 'must contain only alphanumeric characters and/or @.'

Resources:
  # Create a Secret in AWS Secrets Manager
  SumoFlowiseSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Join ["-", [!Ref Stage, Secret, !Ref CurrentEnv]]
      Description: "Database credentials for Flowise application"
      SecretString: !Sub |
        {
          "username": "${Username}",
          "password": "${Password}"
        }
      GenerateSecretString:
        SecretStringTemplate: !Sub '{"username": "${Username}"}'
        GenerateStringKey: !Ref Password
        PasswordLength: 30
        ExcludeCharacters: '"@/\'
      Tags:
        - Key: Name
          Value: !Join ["-", [!Ref Stage, Secret, !Ref CurrentEnv]]
        - Key: CurrentEnv
          Value: !Ref CurrentEnv

  # Grant ECS Task Execution Role Access to Secrets Manager
  ECSSecretsAccessPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "ECSSecretsAccessPolicy-${Stage}"
      Roles:
        - !ImportValue
          Fn::Join: ["-", [!Ref Stage, "ECSTaskExecutionRoleArn", !Ref CurrentEnv]]  # Import the ECS Task Execution Role ARN
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
              - secretsmanager:DescribeSecret
            Resource: !Ref SumoFlowiseSecret

Outputs:
  SumoFlowiseSecretId:
    Description: 'The ID of the secret'
    Value: !Ref SumoFlowiseSecret
    Export:
      Name: !Join ["-", [!Ref Stage, SecretId, !Ref CurrentEnv]]

