AWSTemplateFormatVersion: "2010-09-09"

Description: This template creates resources for Flowise application

Parameters:
  Stage:
    Description: Prefix of resource names
    Type: String
    Default: sumo-flowise

  CurrentEnv:
    Description: "Deployment environment (e.g., dev, prod)"
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

Resources:
  # Create a Secret in AWS Secrets Manager
  SumoFlowiseSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Join ["-", [!Ref Stage, secret, !Ref CurrentEnv]]
      Description: "Database credentials for Flowise application"
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: "password"
        ExcludeCharacters: "!\"#$%&'()*+,./:;<=>?@[\\]^_`{|}~"
        ExcludeLowercase: false
        ExcludeNumbers: false
        ExcludeUppercase: false
        IncludeSpace: false
        PasswordLength: 30
      Tags:
        - Key: Name
          Value: !Join ["-", [!Ref Stage, secret, !Ref CurrentEnv]]
        - Key: CurrentEnv
          Value: !Ref CurrentEnv

  SumoFlowiseSecretRotation:
    Type: AWS::SecretsManager::RotationSchedule
    Properties:
      SecretId: !Ref SumoFlowiseSecret
      RotationLambdaARN: !ImportValue 
        Fn::Join: ["-", [!Ref Stage, RotateLambdaArn, !Ref CurrentEnv]]    
      RotationRules:
        AutomaticallyAfterDays: 1 # Rotate every day

Outputs:
  SumoFlowiseSecretArn:
    Description: 'The Arn of the secret'
    Value: !Ref SumoFlowiseSecret
    Export:
      Name: !Join ["-", [!Ref Stage, SecretArn, !Ref CurrentEnv]]
