Parameters:
    App:
        Type: String
        Description: Your application's name.
    Env:
        Type: String
        Description: The environment name your service, job, or workflow is being deployed to.
    Name:
        Type: String
        Description: Your workload's name.

Resources:
    # Allow frontend service to access S3 storage bucket
    FrontendS3AccessPolicy:
        Type: AWS::IAM::ManagedPolicy
        Properties:
            Description: Grants frontend service access to the shared S3 storage bucket
            PolicyDocument:
                Version: '2012-10-17'
                Statement:
                    - Sid: S3BucketAccess
                      Effect: Allow
                      Action:
                          - s3:GetObject
                          - s3:PutObject
                          - s3:DeleteObject
                          - s3:ListBucket
                      Resource:
                          - !Sub 'arn:aws:s3:::${App}-${Env}-theansweraiserverstorage/*'
                          - !Sub 'arn:aws:s3:::${App}-${Env}-theansweraiserverstorage'

    # Output the backend service endpoint for frontend to use
    BackendServiceEndpoint:
        Type: AWS::SSM::Parameter
        Properties:
            Name: !Sub /${App}/${Env}/flowise-endpoint
            Type: String
            Value: !Sub 'http://flowise.${Env}.${App}.local:4000'
            Description: Internal endpoint for the flowise backend service

Outputs:
    FrontendS3AccessPolicyArn:
        Description: IAM Managed Policy ARN for S3 access
        Value: !Ref FrontendS3AccessPolicy
