openapi: 3.0.0
info:
    title: Hello World API
    description: A simple API to test the OpenAPI documentation setup
    version: 1.0.0
    contact:
        name: AnswerAI Support
        url: https://theanswer.ai
        email: support@theanswer.ai
servers:
    - url: https://api.example.com/v1
      description: Production server
    - url: https://staging-api.example.com/v1
      description: Staging server
tags:
    - name: greeting
      description: Greeting operations
paths:
    /hello:
        get:
            summary: Get a greeting
            description: Returns a friendly greeting message
            operationId: getHello
            tags:
                - greeting
            parameters:
                - name: name
                  in: query
                  description: Name of the person to greet
                  required: false
                  schema:
                      type: string
            responses:
                '200':
                    description: Successful operation
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                        example: 'Hello, World!'
                                    timestamp:
                                        type: string
                                        format: date-time
                                        example: '2023-03-01T12:00:00Z'
                '400':
                    description: Bad request
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: string
                                        example: 'Invalid request'
    /hello/{name}:
        get:
            summary: Get a personalized greeting
            description: Returns a personalized greeting for a specific name
            operationId: getPersonalizedHello
            tags:
                - greeting
            parameters:
                - name: name
                  in: path
                  description: Name of the person to greet
                  required: true
                  schema:
                      type: string
            responses:
                '200':
                    description: Successful operation
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                        example: 'Hello, John!'
                                    timestamp:
                                        type: string
                                        format: date-time
                                        example: '2023-03-01T12:00:00Z'
                '404':
                    description: Name not found
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: string
                                        example: 'Name not found'
components:
    schemas:
        Greeting:
            type: object
            properties:
                message:
                    type: string
                    description: The greeting message
                timestamp:
                    type: string
                    format: date-time
                    description: The time when the greeting was generated
            required:
                - message
                - timestamp
