# Use the official Node.js image as the base image
FROM node:20.15.0

# Set the working directory inside the container
WORKDIR /usr/src/app

# Install pnpm globally
RUN npm install -g pnpm@9.0.4

# Copy the application code to the working directory
COPY . .

# Install dependencies using pnpm
RUN pnpm install

# Build the project
RUN pnpm build

# Expose the port the app runs on
EXPOSE 3000

# Define the command to run the application
CMD ["pnpm", "start"]
