version: '3.1'

services:
    redis:
        image: redis:alpine
        container_name: flowise-redis
        ports:
            - '6379:6379'
        volumes:
            - redis_data:/data
        networks:
            - flowise-net
        restart: always

    flowise:
        image: flowiseai/flowise:latest
        container_name: flowise-main
        restart: always
        ports:
            - '${PORT:-3000}:${PORT:-3000}'
        volumes:
            - ~/.flowise:/root/.flowise
        env_file:
            - .env
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:${PORT:-3000}/api/v1/ping']
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s
        entrypoint: /bin/sh -c "sleep 3; flowise start"
        depends_on:
            - redis
        networks:
            - flowise-net

    flowise-worker:
        image: flowiseai/flowise-worker:latest
        container_name: flowise-worker
        restart: always
        volumes:
            - ~/.flowise:/root/.flowise
        env_file:
            - .env
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:${WORKER_PORT:-5566}/healthz']
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s
        entrypoint: /bin/sh -c "node /app/healthcheck/healthcheck.js & sleep 5 && pnpm run start-worker"
        depends_on:
            - redis
            - flowise
        networks:
            - flowise-net

volumes:
    redis_data:
        driver: local

networks:
    flowise-net:
        driver: bridge
