import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
    docs: [
        'intro',
        {
            type: 'category',
            label: 'Using AnswerAI',
            link: {
                type: 'generated-index',
                title: 'Using AnswerAI',
                description: 'Learn how to use AnswerAI effectively'
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'using-answerai'
                }
            ]
        },
        {
            type: 'category',
            label: 'Developers',
            link: {
                type: 'generated-index',
                title: 'Developer Resources',
                description: 'Technical documentation for developers'
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'developers'
                },
                {
                    type: 'category',
                    label: 'API Reference',
                    link: {
                        type: 'generated-index',
                        title: 'API Reference',
                        description: 'Explore our API documentation'
                    },
                    items: [
                        {
                            type: 'category',
                            label: 'Hello World API',
                            link: {
                                type: 'doc',
                                id: 'api/hello-world/hello-world-api'
                            },
                            items: [
                                {
                                    type: 'autogenerated',
                                    dirName: 'api/hello-world'
                                }
                            ]
                        },
                        {
                            type: 'category',
                            label: 'Assistants API',
                            link: {
                                type: 'doc',
                                id: 'api/assistants/assistants-api'
                            },
                            items: [
                                {
                                    type: 'autogenerated',
                                    dirName: 'api/assistants'
                                }
                            ]
                        },
                        {
                            type: 'category',
                            label: 'Attachments API',
                            link: {
                                type: 'doc',
                                id: 'api/attachments/attachments-api'
                            },
                            items: [
                                {
                                    type: 'autogenerated',
                                    dirName: 'api/attachments'
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            type: 'category',
            label: 'Use Cases',
            link: {
                type: 'generated-index',
                title: 'AnswerAI Use Cases',
                description: 'Explore various applications of AnswerAI'
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'use-cases'
                }
            ]
        },
        {
            type: 'category',
            label: 'Community',
            link: {
                type: 'generated-index',
                title: 'Community Resources',
                description: 'Join the AnswerAI community'
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'community'
                }
            ]
        }
    ]
}

export default sidebars
