import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
    docs: [
        'intro',
        {
            type: 'category',
            label: 'Agent Apps',
            link: {
                type: 'doc',
                id: 'apps'
            },
            items: []
        },
        {
            type: 'category',
            label: 'Browser Extension',
            link: {
                type: 'doc',
                id: 'browser/README'
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'browser'
                }
            ]
        },
        {
            type: 'category',
            label: 'Chatbot',
            link: {
                type: 'doc',
                id: 'chat/README'
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'chat'
                }
            ]
        },
        {
            type: 'category',
            label: 'Studio',
            link: {
                type: 'doc',
                id: 'sidekick-studio/README'
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'sidekick-studio'
                }
            ]
        },
        {
            type: 'category',
            label: 'Developers',
            link: {
                type: 'generated-index',
                title: 'Developer Resources',
                description: 'Technical documentation for developers'
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'developers'
                },
                {
                    type: 'category',
                    label: 'API Reference',
                    link: {
                        type: 'doc',
                        id: 'api/index'
                    },
                    items: [
                        {
                            type: 'doc',
                            id: 'api/full-api-spec',
                            label: 'Full API Specification'
                        },
                        {
                            type: 'category',
                            label: 'Assistants API',
                            link: {
                                type: 'doc',
                                id: 'api/assistants/assistants-api'
                            },
                            items: [
                                {
                                    type: 'autogenerated',
                                    dirName: 'api/assistants'
                                }
                            ]
                        },
                        {
                            type: 'category',
                            label: 'Attachments API',
                            link: {
                                type: 'doc',
                                id: 'api/attachments/attachments-api'
                            },
                            items: [
                                {
                                    type: 'autogenerated',
                                    dirName: 'api/attachments'
                                }
                            ]
                        },
                        {
                            type: 'category',
                            label: 'Chat Message API',
                            link: {
                                type: 'doc',
                                id: 'api/chat-message/chat-message-api'
                            },
                            items: [
                                {
                                    type: 'autogenerated',
                                    dirName: 'api/chat-message'
                                }
                            ]
                        },
                        {
                            type: 'category',
                            label: 'Leads API',
                            link: {
                                type: 'doc',
                                id: 'api/leads/leads-api'
                            },
                            items: [
                                {
                                    type: 'autogenerated',
                                    dirName: 'api/leads'
                                }
                            ]
                        },
                        {
                            type: 'category',
                            label: 'Prediction API',
                            link: {
                                type: 'doc',
                                id: 'api/prediction/prediction-api'
                            },
                            items: [
                                {
                                    type: 'autogenerated',
                                    dirName: 'api/prediction'
                                }
                            ]
                        },
                        {
                            type: 'category',
                            label: 'Chatflows API',
                            link: {
                                type: 'doc',
                                id: 'api/chatflows/chatflows-api'
                            },
                            items: [
                                {
                                    type: 'autogenerated',
                                    dirName: 'api/chatflows'
                                }
                            ]
                        },
                        {
                            type: 'category',
                            label: 'Document Store API',
                            link: {
                                type: 'doc',
                                id: 'api/document-store/document-store-api'
                            },
                            items: [
                                {
                                    type: 'autogenerated',
                                    dirName: 'api/document-store'
                                }
                            ]
                        },
                        {
                            type: 'category',
                            label: 'Feedback API',
                            link: {
                                type: 'doc',
                                id: 'api/feedback/feedback-api'
                            },
                            items: [
                                {
                                    type: 'autogenerated',
                                    dirName: 'api/feedback'
                                }
                            ]
                        },
                        {
                            type: 'category',
                            label: 'Tools API',
                            link: {
                                type: 'doc',
                                id: 'api/tools/tools-api'
                            },
                            items: [
                                {
                                    type: 'autogenerated',
                                    dirName: 'api/tools'
                                }
                            ]
                        },
                        {
                            type: 'category',
                            label: 'Ping API',
                            link: {
                                type: 'doc',
                                id: 'api/ping/ping-api'
                            },
                            items: [
                                {
                                    type: 'autogenerated',
                                    dirName: 'api/ping'
                                }
                            ]
                        },
                        {
                            type: 'category',
                            label: 'Upsert History API',
                            link: {
                                type: 'doc',
                                id: 'api/upsert-history/upsert-history-api'
                            },
                            items: [
                                {
                                    type: 'autogenerated',
                                    dirName: 'api/upsert-history'
                                }
                            ]
                        },
                        {
                            type: 'category',
                            label: 'Variables API',
                            link: {
                                type: 'doc',
                                id: 'api/variables/variables-api'
                            },
                            items: [
                                {
                                    type: 'autogenerated',
                                    dirName: 'api/variables'
                                }
                            ]
                        },
                        {
                            type: 'category',
                            label: 'Vector Upsert API',
                            link: {
                                type: 'doc',
                                id: 'api/vector-upsert/vector-upsert-api'
                            },
                            items: [
                                {
                                    type: 'autogenerated',
                                    dirName: 'api/vector-upsert'
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            type: 'category',
            label: 'Learn',
            link: {
                type: 'generated-index',
                title: 'Learn AI & Master AnswerAgentAI',
                description: 'Master AI fundamentals and explore practical use cases'
            },
            items: [
                {
                    type: 'doc',
                    id: 'use-cases/README',
                    label: 'Use Cases'
                },
                {
                    type: 'category',
                    label: 'AI Learning Modules',
                    items: [
                        'use-cases/module-1-welcome-to-ai',
                        'use-cases/module-2-art-of-the-prompt',
                        'use-cases/module-3-answeragent-in-action',
                        'use-cases/module-4-answeragent-vs-others',
                        'use-cases/module-5-supercharging-answeragent'
                    ]
                },
                {
                    type: 'link',
                    label: '📺 Digital at Scale YouTube',
                    href: 'https://www.youtube.com/@digitalatscale'
                },
                {
                    type: 'doc',
                    id: 'use-cases/agent-use-cases',
                    label: 'Agent Use Cases (40 Examples)'
                }
            ]
        },
        {
            type: 'category',
            label: 'Support',
            link: {
                type: 'generated-index',
                title: 'Support Resources',
                description: 'Get help with AnswerAgentAI'
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'community'
                }
            ]
        }
    ]
}

export default sidebars
