#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Running a quick format (assuming this is a custom script you've set up)
yarn quick

# Running Prettier format
yarn format

# Running Prettier format check
yarn format:check

# Running ESLint through lint-staged
yarn lint-staged
