name: Sumo Chatwoot for Development

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Validate Cloudformation
        run: |
          aws cloudformation validate-template \
            --template-body file://aws-cloudformation/ecs.yml

      - name: Network-Cloudformation
        run: |
          STACK_NAME=sumo-flowise-ecs-stack-dev
          aws cloudformation deploy \
            --template-file aws-cloudformation/ecs.yml \
            --parameter-overrides Environment=dev \
            --stack-name $STACK_NAME \
            --capabilities CAPABILITY_NAMED_IAM

          echo "CloudFormation Outputs:"
          aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[0].Outputs' --output table

      - name: EC2-Cloudformation
        run: |
          STACK_NAME=sumo-flowise-ec2-stack-dev
          aws cloudformation deploy \
            --template-file aws-cloudformation/ec2.yml \
            --parameter-overrides \
              Environment=dev \
              KeyName=${{ secrets.KEY_NAME }} \
            --stack-name $STACK_NAME \
            --capabilities CAPABILITY_NAMED_IAM

          echo "CloudFormation Outputs:"
          aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[0].Outputs' --output table

          SumoFlowisePublicIP=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query "Stacks[0].Outputs[?OutputKey=='SumoFlowisePublicIP'].OutputValue" --output text)
          echo "EC2_IP=${SumoFlowisePublicIP}" >> $GITHUB_ENV

          SumoFlowiseWebAppURL=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query "Stacks[0].Outputs[?OutputKey=='SumoFlowiseWebAppURL'].OutputValue" --output text)
          echo "EC2_ID=${SumoFlowiseWebAppURL}" >> $GITHUB_ENV

