name: Deploy to ECS

on:
  push:
    branches:
      - develop # Trigger deployment on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Validate Cloudformation
      run: |
        aws cloudformation validate-template \
          --template-body file://aws-cloudformation/vpc.yml
        aws cloudformation validate-template \
          --template-body file://aws-cloudformation/alb.yml
        aws cloudformation validate-template \
          --template-body file://aws-cloudformation/postgre.yml
        aws cloudformation validate-template \
          --template-body file://aws-cloudformation/ecs.yml
        aws cloudformation validate-template \
          --template-body file://aws-cloudformation/efs.yml
        aws cloudformation validate-template \
          --template-body file://aws-cloudformation/iam.yml
        aws cloudformation validate-template \
          --template-body file://aws-cloudformation/ecr.yml
        aws cloudformation validate-template \
          --template-body file://aws-cloudformation/flowise.yml
        aws cloudformation validate-template \
          --template-body file://aws-cloudformation/route.yml

      
    # Step 2: Log in to Amazon ECR
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    # Step 4: Deploy updated image using CloudFormation
    - name: VPC-CloudFormation
      env:
        STACK_NAME: sumo-flowise-vpc-stack-dev
        CURRENTENV: dev
      run: |
        aws cloudformation deploy \
          --stack-name $STACK_NAME \
          --template-file aws-cloudformation/vpc.yml \
          --parameter-overrides \
            CurrentEnv=$CURRENTENV \
          --capabilities CAPABILITY_NAMED_IAM

          echo "CloudFormation Outputs:"
          aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[0].Outputs' --output table

    - name: ALB-CloudFormation
      env:
        STACK_NAME: sumo-flowise-alb-stack-dev
        CURRENTENV: dev
        CERTIFICATEARN: ${{ secrets.ACM_CERTIFICATE_ARN }}
      run: |
        aws cloudformation deploy \
          --stack-name $STACK_NAME \
          --template-file aws-cloudformation/alb.yml \
          --parameter-overrides \
            CurrentEnv=$CURRENTENV \
            SumoFlowiseCertificateArn=$CERTIFICATEARN \
          --capabilities CAPABILITY_NAMED_IAM

          echo "CloudFormation Outputs:"
          aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[0].Outputs' --output table

    - name: Postgre-Cloudformation
      env:
        STACK_NAME: sumo-flowise-postgre-stack-dev
        CURRENTENV: dev
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        aws cloudformation deploy \
          --template-file aws-cloudformation/postgre.yml \
          --stack-name $STACK_NAME \
          --parameter-overrides \
            CurrentEnv=$CURRENTENV \
            DBUsername=$USERNAME \
            DBPassword=$PASSWORD \
          --capabilities CAPABILITY_NAMED_IAM

        echo "CloudFormation Outputs:"
        aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[0].Outputs' --output table

        SumoFlowiseRDSInstanceEndpoint=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query "Stacks[0].Outputs[?OutputKey=='SumoFlowiseRDSInstanceEndpoint'].OutputValue" --output text)
        echo "POSTGRES_HOST=${SumoFlowiseRDSInstanceEndpoint}" >> $GITHUB_ENV

    - name: ECS-CloudFormation
      env:
        STACK_NAME: sumo-flowise-ecs-stack-dev
        CURRENTENV: dev
      run: |
        aws cloudformation deploy \
          --stack-name $STACK_NAME \
          --template-file aws-cloudformation/ecs.yml \
          --parameter-overrides \
            CurrentEnv=$CURRENTENV \
          --capabilities CAPABILITY_NAMED_IAM

          echo "CloudFormation Outputs:"
          aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[0].Outputs' --output table

    - name: EFS-CloudFormation
      env:
        STACK_NAME: sumo-flowise-efs-stack-dev
        CURRENTENV: dev
      run: |
        aws cloudformation deploy \
          --stack-name $STACK_NAME \
          --template-file aws-cloudformation/efs.yml \
          --parameter-overrides \
            CurrentEnv=$CURRENTENV \
          --capabilities CAPABILITY_NAMED_IAM

          echo "CloudFormation Outputs:"
          aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[0].Outputs' --output table

    - name: IAM-CloudFormation
      env:
        STACK_NAME: sumo-flowise-iam-stack-dev
        CURRENTENV: dev
      run: |
        aws cloudformation deploy \
          --stack-name $STACK_NAME \
          --template-file aws-cloudformation/iam.yml \
          --parameter-overrides \
            CurrentEnv=$CURRENTENV \
          --capabilities CAPABILITY_NAMED_IAM

          echo "CloudFormation Outputs:"
          aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[0].Outputs' --output table

    - name: ECR-CloudFormation
      env:
        STACK_NAME: sumo-flowise-ecr-stack-dev
        CURRENTENV: dev
      run: |
        aws cloudformation deploy \
          --stack-name $STACK_NAME \
          --template-file aws-cloudformation/ecr.yml \
          --parameter-overrides \
            CurrentEnv=$CURRENTENV \
          --capabilities CAPABILITY_NAMED_IAM

        echo "CloudFormation Outputs:"
        aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[0].Outputs' --output table

        SumoFlowiseECRRepositoryUri=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query "Stacks[0].Outputs[?OutputKey=='SumoFlowiseECRRepositoryUri'].OutputValue" --output text)
        echo "REPOSITORY_URI=${SumoFlowiseECRRepositoryUri}" >> $GITHUB_ENV

    - name: Build, tag, and push Docker image to Amazon ECR
      env:
        ECR_REPOSITORY: sumo-flowise-app-dev
        REPOSITORY_URI: ${{ env.REPOSITORY_URI }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Build Docker image
        docker build -t $REPOSITORY_URI:$IMAGE_TAG .
        
        # Push Docker image to ECR
        docker push $REPOSITORY_URI:$IMAGE_TAG
        
    - name: ECS2-CloudFormation
      env:
        STACK_NAME: sumo-flowise-ecs2-stack-dev
        CURRENTENV: dev
        REPOSITORY_URI: ${{ env.REPOSITORY_URI }}
        IMAGE_TAG: ${{ github.sha }}
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        aws cloudformation deploy \
          --stack-name $STACK_NAME \
          --template-file aws-cloudformation/flowise.yml \
          --parameter-overrides \
            CurrentEnv=$CURRENTENV \
            DBUsername=$USERNAME \
            DBPassword=$PASSWORD \
            ECRImageUrl=$REPOSITORY_URI \
            ImageTag=$IMAGE_TAG \
          --capabilities CAPABILITY_NAMED_IAM

          echo "CloudFormation Outputs:"
          aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[0].Outputs' --output table

    - name: Route53-Cloudformation
      env:
        STACK_NAME: sumo-flowise-route-stack-dev
        CURRENTENV: dev
        HOSTZONE_ID: ${{ secrets.ROUTE_HZ_ID }}
      run: |
        aws cloudformation deploy \
          --template-file aws-cloudformation/route.yml \
          --stack-name $STACK_NAME \
          --parameter-overrides \
            CurrentEnv=$CURRENTENV \
            HostedZoneId=$HOSTZONE_ID \
          --capabilities CAPABILITY_NAMED_IAM

        echo "CloudFormation Outputs:"
        aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[0].Outputs' --output table

        echo "Wait for creating domain"
        sleep 60

    - name: Post-deployment script
      env:
        STACK_NAME: sumo-flowise-route-stack-dev
      run: |
        DomainName=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query "Stacks[0].Outputs[?OutputKey=='RecordSetName'].OutputValue" --output text)
        echo "Deployment complete!\n Check the url: https://${DomainName}"
        