name: release

on:
    push:
        branches:
            - production
    workflow_dispatch:

permissions:
    contents: write
    issues: read
    pull-requests: read

jobs:
    release:
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Semantic Release
              uses: cycjimmy/semantic-release-action@v4
              with:
                  extra_plugins: |
                      @semantic-release/commit-analyzer
                      @semantic-release/release-notes-generator
                      @semantic-release/changelog
                      @semantic-release/git
                      @semantic-release/github
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    dry-run:
        if: github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Semantic Release (dry run)
              uses: cycjimmy/semantic-release-action@v4
              with:
                  dry_run: true
                  extra_plugins: |
                      @semantic-release/commit-analyzer
                      @semantic-release/release-notes-generator
                      @semantic-release/changelog
                      @semantic-release/git
                      @semantic-release/github
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
