name: Release

on:
    push:
        branches:
            - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
        steps:
            - uses: actions/checkout@v6

            - uses: pnpm/action-setup@v6
              with:
                  version: 10.26.0

            - uses: actions/setup-node@v6
              with:
                  node-version: '20.20.2'
                  registry-url: 'https://registry.npmjs.org'

            - name: Install dependencies
              run: pnpm install --frozen-lockfile
              env:
                  PUPPETEER_SKIP_DOWNLOAD: 'true'

            - name: Create Release Pull Request or Publish
              uses: changesets/action@v1
              with:
                  publish: pnpm changeset:publish
                  title: 'chore: version packages'
                  commit: 'chore: version packages'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
