name: Test Docker Build

on:
    push:
        branches:
            - main

    pull_request:
        branches:
            - '*'
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        env:
            PUPPETEER_SKIP_DOWNLOAD: true
        steps:
            - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
            - run: docker build --no-cache -t flowise .
